BEGIN;

-- Validation is complete, so the final swap only holds brief metadata locks.
ALTER TABLE "action_approval_rules" DROP CONSTRAINT "action_approval_rules_workspaceId_fkey";
ALTER TABLE "action_approval_rules" RENAME CONSTRAINT "action_approval_rules_workspace_fkey" TO "action_approval_rules_workspaceId_fkey";
ALTER TABLE "action_auto_review_preferences" DROP CONSTRAINT "action_auto_review_preferences_workspaceId_fkey";
ALTER TABLE "action_auto_review_preferences" RENAME CONSTRAINT "action_auto_review_preferences_workspace_fkey" TO "action_auto_review_preferences_workspaceId_fkey";
ALTER TABLE "bots" DROP CONSTRAINT "bots_workspaceId_fkey";
ALTER TABLE "bots" RENAME CONSTRAINT "bots_workspace_fkey" TO "bots_workspaceId_fkey";
ALTER TABLE "bot_sections" DROP CONSTRAINT "bot_sections_workspaceId_fkey";
ALTER TABLE "bot_sections" RENAME CONSTRAINT "bot_sections_workspace_fkey" TO "bot_sections_workspaceId_fkey";
ALTER TABLE "bot_deletions" DROP CONSTRAINT "bot_deletions_workspaceId_fkey";
ALTER TABLE "bot_deletions" RENAME CONSTRAINT "bot_deletions_workspace_fkey" TO "bot_deletions_workspaceId_fkey";
ALTER TABLE "chat_groups" DROP CONSTRAINT "chat_groups_workspaceId_fkey";
ALTER TABLE "chat_groups" RENAME CONSTRAINT "chat_groups_workspace_fkey" TO "chat_groups_workspaceId_fkey";
ALTER TABLE "threads" DROP CONSTRAINT "threads_workspaceId_fkey";
ALTER TABLE "threads" RENAME CONSTRAINT "threads_workspace_fkey" TO "threads_workspaceId_fkey";
ALTER TABLE "events" DROP CONSTRAINT "events_workspaceId_fkey";
ALTER TABLE "events" RENAME CONSTRAINT "events_workspace_fkey" TO "events_workspaceId_fkey";
ALTER TABLE "tasks" DROP CONSTRAINT "tasks_workspaceId_fkey";
ALTER TABLE "tasks" RENAME CONSTRAINT "tasks_workspace_fkey" TO "tasks_workspaceId_fkey";
ALTER TABLE "runs" DROP CONSTRAINT "runs_workspaceId_fkey";
ALTER TABLE "runs" RENAME CONSTRAINT "runs_workspace_fkey" TO "runs_workspaceId_fkey";
ALTER TABLE "external_effects" DROP CONSTRAINT "external_effects_workspaceId_fkey";
ALTER TABLE "external_effects" RENAME CONSTRAINT "external_effects_workspace_fkey" TO "external_effects_workspaceId_fkey";
ALTER TABLE "routines" DROP CONSTRAINT "routines_workspaceId_fkey";
ALTER TABLE "routines" RENAME CONSTRAINT "routines_workspace_fkey" TO "routines_workspaceId_fkey";
ALTER TABLE "scratchpad_items" DROP CONSTRAINT "scratchpad_items_workspaceId_fkey";
ALTER TABLE "scratchpad_items" RENAME CONSTRAINT "scratchpad_items_workspace_fkey" TO "scratchpad_items_workspaceId_fkey";
ALTER TABLE "taught_skills" DROP CONSTRAINT "taught_skills_workspaceId_fkey";
ALTER TABLE "taught_skills" RENAME CONSTRAINT "taught_skills_workspace_fkey" TO "taught_skills_workspaceId_fkey";
ALTER TABLE "agent_skills" DROP CONSTRAINT "agent_skills_workspaceId_fkey";
ALTER TABLE "agent_skills" RENAME CONSTRAINT "agent_skills_workspace_fkey" TO "agent_skills_workspaceId_fkey";
ALTER TABLE "connections" DROP CONSTRAINT "connections_workspaceId_fkey";
ALTER TABLE "connections" RENAME CONSTRAINT "connections_workspace_fkey" TO "connections_workspaceId_fkey";
ALTER TABLE "capability_installs" DROP CONSTRAINT "capability_installs_workspaceId_fkey";
ALTER TABLE "capability_installs" RENAME CONSTRAINT "capability_installs_workspace_fkey" TO "capability_installs_workspaceId_fkey";
ALTER TABLE "memory_documents" DROP CONSTRAINT "memory_documents_workspaceId_fkey";
ALTER TABLE "memory_documents" RENAME CONSTRAINT "memory_documents_workspace_fkey" TO "memory_documents_workspaceId_fkey";
ALTER TABLE "agent_homes" DROP CONSTRAINT "agent_homes_workspaceId_fkey";
ALTER TABLE "agent_homes" RENAME CONSTRAINT "agent_homes_workspace_fkey" TO "agent_homes_workspaceId_fkey";
ALTER TABLE "browser_profiles" DROP CONSTRAINT "browser_profiles_workspaceId_fkey";
ALTER TABLE "browser_profiles" RENAME CONSTRAINT "browser_profiles_workspace_fkey" TO "browser_profiles_workspaceId_fkey";
ALTER TABLE "computers" DROP CONSTRAINT "computers_workspaceId_fkey";
ALTER TABLE "computers" RENAME CONSTRAINT "computers_workspace_fkey" TO "computers_workspaceId_fkey";
ALTER TABLE "artifacts" DROP CONSTRAINT "artifacts_workspaceId_fkey";
ALTER TABLE "artifacts" RENAME CONSTRAINT "artifacts_workspace_fkey" TO "artifacts_workspaceId_fkey";
ALTER TABLE "usage_records" DROP CONSTRAINT "usage_records_workspaceId_fkey";
ALTER TABLE "usage_records" RENAME CONSTRAINT "usage_records_workspace_fkey" TO "usage_records_workspaceId_fkey";
ALTER TABLE "notification_preferences" DROP CONSTRAINT "notification_preferences_workspaceId_fkey";
ALTER TABLE "notification_preferences" RENAME CONSTRAINT "notification_preferences_workspace_fkey" TO "notification_preferences_workspaceId_fkey";
ALTER TABLE "workspace_memory_configs" DROP CONSTRAINT "workspace_memory_configs_workspaceId_fkey";
ALTER TABLE "workspace_memory_configs" RENAME CONSTRAINT "workspace_memory_configs_workspace_fkey" TO "workspace_memory_configs_workspaceId_fkey";
ALTER TABLE "mcp_servers" DROP CONSTRAINT "mcp_servers_workspaceId_fkey";
ALTER TABLE "mcp_servers" RENAME CONSTRAINT "mcp_servers_workspace_fkey" TO "mcp_servers_workspaceId_fkey";

COMMIT;
